name: Using my custom JavaScript action
on:
  push:
    branches:
      - main

jobs:
  my-custom-javasctip-action-job:
    name: A job to say hello
    runs-on: ubuntu-latest

    steps:
      - name: Hello world action step
        id: hello
        uses: josecueva/my-first-custom-github-action@v1.0
        with:
          name: Meeeeeeeee

      # Use the output from the `hello` step
      - name: Get the greeting
        run: echo "${{ steps.hello.outputs.greeting }}"
