name: Workflow Commands
on: [push]

jobs:
  my-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Env Variable
        run: echo "MY_ENV_VAR=HelloWorld" >> $GITHUB_ENV
      - name: Read Env Variable
        run: echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
      - name: Add Path to directory
        run: echo "/my/custom/path" >> $GITHUB_PATH
      - name: Verify Path Addition
        run: echo "Current PATH is $PATH"
      - name: Create Output Variable
        id: set-output
        run: echo "my_output=OutputValue" >> $GITHUB_OUTPUT
      - name: Read Output Variable
        run: echo "The output variable is ${{ steps.set-output.outputs.my_output }}"
      - name: Create debug log
        run: echo "::debug::This is a debug message"
      - name: Mask value
        run: |
          echo "::add-mask::SensitiveValue123"
          echo "This is a log with a masked value: SensitiveValue123"
      - name: Grouped Logs
        run: |
          echo "::group::My Grouped Logs"
          echo "This is a log message inside the group."
          echo "::endgroup::"
